// Squire's knowledge base: each topic has keywords used for matching
// and a list of steps shown when that topic is the best match.
const KNOWLEDGE = [
  {
    title: "Shaving with a razor",
    keywords: ["shave", "shaving", "razor", "beard", "stubble"],
    steps: [
      "Wet your face with warm water for 30 seconds to soften the hair.",
      "Apply shaving cream or gel in a thin, even layer.",
      "Shave in the direction the hair grows, using short, light strokes.",
      "Rinse the blade after every stroke to keep it from clogging.",
      "Go over rough spots once more, but never more than twice in one area.",
      "Rinse your face with cold water and pat dry, then apply a moisturizer or alum block.",
    ],
  },
  {
    title: "Tying a tie (Four-in-Hand knot)",
    keywords: ["tie", "necktie", "knot tie", "windsor"],
    steps: [
      "Drape the tie around your neck, wide end on the right, hanging about 12 inches lower than the narrow end.",
      "Cross the wide end over the narrow end.",
      "Bring the wide end back under the narrow end.",
      "Cross the wide end over the narrow end again.",
      "Pull the wide end up through the loop around your neck.",
      "Thread the wide end down through the knot in front, then tighten by pulling the narrow end and sliding the knot up.",
    ],
  },
  {
    title: "Tying a bow tie",
    keywords: ["bow tie", "bowtie"],
    steps: [
      "Drape the bow tie around your neck with one end about 2 inches longer than the other.",
      "Cross the longer end over the shorter end and pass it up through the neck loop.",
      "Fold the shorter end into a bow shape and hold it horizontally against your collar.",
      "Drop the long end straight down over the center of the folded bow.",
      "Fold the long end back and push it through the loop behind the front bow.",
      "Tighten by pulling both bow loops and the knot until it's snug and even.",
    ],
  },
  {
    title: "Changing a flat tire",
    keywords: ["tire", "flat tire", "spare tire", "lug nuts", "jack"],
    steps: [
      "Pull over somewhere flat and safe, turn on hazard lights, and engage the parking brake.",
      "Loosen the lug nuts on the flat tire slightly before jacking up the car.",
      "Place the jack under the car's frame near the flat tire and raise it until the tire is off the ground.",
      "Remove the lug nuts fully and pull off the tire.",
      "Mount the spare tire and hand-tighten the lug nuts in a star pattern.",
      "Lower the car, then fully tighten the lug nuts with a wrench. Drive to a shop to fix or replace the tire soon.",
    ],
  },
  {
    title: "Checking tire pressure",
    keywords: ["tire pressure", "psi", "inflate tire"],
    steps: [
      "Check tires when cold (haven't been driven for at least 3 hours) for an accurate reading.",
      "Remove the valve cap and press a tire gauge firmly onto the valve stem.",
      "Read the PSI and compare it to the number on the sticker inside the driver's door jamb (not the number on the tire itself).",
      "Add air at a gas station pump if low, checking the gauge every few seconds while filling.",
      "Replace the valve cap and repeat for all four tires, including the spare.",
    ],
  },
  {
    title: "Checking and changing engine oil",
    keywords: ["oil", "engine oil", "oil change", "dipstick"],
    steps: [
      "Park on level ground with the engine cool, then locate the dipstick under the hood.",
      "Pull it out, wipe it clean, reinsert fully, then pull it out again to read the level.",
      "If it's low, add the oil type listed in your manual through the oil fill cap.",
      "To fully change oil: place a drain pan under the drain plug, remove the plug, and let it drain.",
      "Replace the drain plug and oil filter, then refill with fresh oil to the correct level.",
      "Check the dipstick again after a minute to confirm the level is correct.",
    ],
  },
  {
    title: "Jump starting a car",
    keywords: ["jump start", "dead battery", "jumper cables", "battery"],
    steps: [
      "Park the working car close to the dead one without the vehicles touching.",
      "Connect a red clamp to the dead battery's positive terminal, then the other red clamp to the good battery's positive terminal.",
      "Connect a black clamp to the good battery's negative terminal, then the other black clamp to an unpainted metal part of the dead car (not the battery).",
      "Start the working car and let it run for a few minutes.",
      "Try starting the dead car. If it starts, let it run for at least 15 minutes before turning it off.",
      "Remove the cables in reverse order: black from the dead car, black from the good car, red from the good car, red from the dead car.",
    ],
  },
  {
    title: "Changing wiper blades",
    keywords: ["wiper blades", "windshield wipers"],
    steps: [
      "Lift the wiper arm away from the windshield until it locks upright.",
      "Find the small tab or clip where the blade attaches to the arm and press or slide it to release.",
      "Slide the old blade off the hooked end of the arm.",
      "Slide the new blade on until it clicks into place securely.",
      "Lower the arm gently back onto the windshield and repeat for the other side.",
    ],
  },
  {
    title: "Unclogging a drain",
    keywords: ["drain", "clog", "clogged", "sink", "shower drain"],
    steps: [
      "Remove any visible hair or debris from the drain cover by hand.",
      "Pour boiling water down the drain to dissolve grease buildup.",
      "If still clogged, use a plunger with a small amount of water in the basin for suction.",
      "Try a drain snake, pushing it in and twisting to grab the clog, then pulling it out.",
      "As a last resort, mix baking soda and vinegar, pour it down, wait 15 minutes, then flush with hot water.",
    ],
  },
  {
    title: "Fixing a running toilet",
    keywords: ["running toilet", "toilet running", "toilet fix", "flapper"],
    steps: [
      "Remove the tank lid and look at the flapper valve at the bottom of the tank.",
      "If the flapper isn't sealing, check that the chain connecting it to the flush lever isn't tangled or too tight.",
      "Check the fill valve float — if water is too high, it can run into the overflow tube constantly; adjust the float lower.",
      "Inspect the flapper for cracks or wear and replace it (cheap part from any hardware store) if it's old or warped.",
      "Flush and watch a full cycle to confirm the water shuts off properly.",
    ],
  },
  {
    title: "Fixing a leaky faucet",
    keywords: ["leaky faucet", "dripping faucet", "faucet leak"],
    steps: [
      "Turn off the water supply valves under the sink before doing anything.",
      "Remove the faucet handle (usually one screw under a decorative cap) to expose the cartridge or valve.",
      "Pull out the worn cartridge, O-ring, or washer causing the drip.",
      "Take it to a hardware store to match the exact replacement part, or buy a universal repair kit.",
      "Install the new part, reassemble the handle, and turn the water back on to test.",
    ],
  },
  {
    title: "Replacing a light switch or outlet",
    keywords: ["light switch", "outlet", "electrical outlet", "replace switch"],
    steps: [
      "Turn off power to that circuit at the breaker box first, then double-check with a voltage tester.",
      "Remove the cover plate and unscrew the switch or outlet from the wall box.",
      "Note which wires connect to which terminals (or take a photo) before disconnecting them.",
      "Connect the same wires to the matching terminals on the new switch or outlet.",
      "Tuck the wires back into the box, screw the device in, attach the cover plate, then restore power and test.",
    ],
  },
  {
    title: "Hanging a picture or shelf",
    keywords: ["hang picture", "hang shelf", "wall mount", "drill into wall"],
    steps: [
      "Decide on placement and mark the spot with a pencil, using a level to keep it straight.",
      "Use a stud finder to locate a wall stud for heavy items — studs hold far more weight than drywall alone.",
      "If no stud is available, use the appropriate drywall anchor for the item's weight.",
      "Drill a pilot hole slightly smaller than your screw or anchor.",
      "Insert the anchor (if used), drive in the screw, and hang the item, checking it's level.",
    ],
  },
  {
    title: "Patching a small drywall hole",
    keywords: ["drywall", "wall hole", "patch wall", "spackle"],
    steps: [
      "Clean loose debris from around the hole and lightly sand the edges smooth.",
      "For small holes, apply spackle with a putty knife directly over the hole, slightly overfilling.",
      "For larger holes, place a self-adhesive mesh patch over the hole first, then spread spackle over it.",
      "Let it dry fully (check the product for time), then sand smooth and flush with the wall.",
      "Apply a thin second coat if needed, sand again, then prime and paint to match the wall.",
    ],
  },
  {
    title: "Ironing a dress shirt",
    keywords: ["iron", "ironing", "dress shirt wrinkle", "wrinkle"],
    steps: [
      "Set the iron temperature based on the fabric (cotton = high, synthetic = low) and let it heat up.",
      "Start with the collar, ironing from the tips inward on both sides.",
      "Iron the cuffs and sleeves next, using a sleeve board or rolling the sleeve flat.",
      "Lay the body of the shirt on the board and iron the back, then each front panel.",
      "Hang the shirt immediately on a hanger so it doesn't wrinkle again while cooling.",
    ],
  },
  {
    title: "Doing laundry without ruining it",
    keywords: ["laundry", "washing machine", "wash clothes", "shrink"],
    steps: [
      "Sort clothes by color (darks, lights, whites) and check care labels for special instructions.",
      "Turn jeans and printed shirts inside out to protect colors and graphics.",
      "Use cold water for colors to prevent fading and bleeding, warm/hot for whites and heavily soiled items.",
      "Don't overload the machine — clothes need room to move for an even wash.",
      "Dry on low heat or air-dry items labeled 'do not tumble dry' to avoid shrinking.",
    ],
  },
  {
    title: "Folding clothes (shirts, pants, t-shirts)",
    keywords: ["fold clothes", "folding clothes", "fold shirt", "fold pants", "fold laundry", "fold a shirt"],
    steps: [
      "T-shirts: lay flat face down, fold one side in along the seam (sleeve included), then the other side so they overlap slightly.",
      "Fold the bottom hem up to the shoulders, then fold in half again for a compact rectangle.",
      "Dress shirts: button it up, lay face down, fold both sides in including the sleeves, then fold in thirds from the bottom up to keep it crease-free.",
      "Pants: fold in half lengthwise (matching the legs), then fold in half or thirds from the waist down.",
      "Stack folded items by type in drawers so you can see and grab them without digging through a pile.",
    ],
  },
  {
    title: "Packing a suitcase",
    keywords: ["pack suitcase", "packing", "pack a bag", "packing for a trip"],
    steps: [
      "Roll casual clothes (t-shirts, athletic wear) to save space and reduce wrinkles.",
      "Fold dress shirts and structured items flat instead of rolling, to avoid creases.",
      "Place heavier items (shoes, toiletry bags) near the wheels/bottom of the suitcase for balance.",
      "Stuff socks or small items inside shoes to save space, and pack shoes along the edges.",
      "Use packing cubes or plastic bags to separate categories (clothes, electronics, toiletries) and keep things organized.",
    ],
  },
  {
    title: "Washing dishes by hand",
    keywords: ["wash dishes", "washing dishes", "dishes", "do the dishes"],
    steps: [
      "Scrape off excess food into the trash or compost before washing.",
      "Fill the sink (or a basin) with hot water and a squirt of dish soap to create suds.",
      "Wash least-dirty items first (glasses, utensils) and greasiest items last (pots, pans) so you don't have to change the water as often.",
      "Scrub with a sponge or brush, paying extra attention to the underside and rims where grime hides.",
      "Rinse thoroughly under running water to remove all soap residue, then air-dry in a rack or towel-dry immediately.",
    ],
  },
  {
    title: "Polishing and shining shoes",
    keywords: ["shine shoes", "polish shoes", "shoe polish"],
    steps: [
      "Remove laces and brush off any dirt or dust with a horsehair brush.",
      "Apply a small amount of polish in circular motions with a soft cloth, covering the whole shoe.",
      "Let it sit for a few minutes to let the polish soak into the leather.",
      "Buff vigorously with a clean cloth or brush until the polish is no longer cloudy.",
      "For an extra shine, lightly dampen a cloth, add a drop of polish, and buff in tight circles ('spit shine').",
    ],
  },
  {
    title: "Sewing a button back on",
    keywords: ["sew", "button", "sewing", "needle and thread"],
    steps: [
      "Thread a needle and tie a knot at the end, doubling the thread for strength.",
      "Position the button where it belongs and push the needle up through one hole, then down through another.",
      "Repeat 5-6 times through each pair of holes, keeping the stitches a little loose.",
      "On the last pass, wrap the thread a few times around the stitches under the button to form a thread shank.",
      "Push the needle through to the back of the fabric and tie off with a few small knots, then trim the thread.",
    ],
  },
  {
    title: "Cooking a basic steak",
    keywords: ["steak", "cook steak", "sear steak"],
    steps: [
      "Take the steak out of the fridge 30 minutes before cooking so it reaches room temperature.",
      "Pat it dry and season generously with salt and pepper on both sides.",
      "Heat a heavy skillet (cast iron is ideal) over high heat with a bit of oil until it's almost smoking.",
      "Sear 2-3 minutes per side without moving it, then add butter, garlic, and herbs if desired.",
      "Use a meat thermometer: 130°F for medium-rare, 140°F for medium.",
      "Rest the steak for 5 minutes off the heat before cutting so the juices redistribute.",
    ],
  },
  {
    title: "Cooking perfect rice",
    keywords: ["cook rice", "rice", "boil rice"],
    steps: [
      "Rinse the rice in cold water until the water runs mostly clear, to remove excess starch.",
      "Use a 1:1.5 ratio of rice to water for white rice (e.g. 1 cup rice to 1.5 cups water).",
      "Bring to a boil uncovered, then reduce to the lowest heat and cover with a tight lid.",
      "Cook for about 15-18 minutes without lifting the lid.",
      "Turn off the heat and let it sit covered for 5-10 minutes, then fluff with a fork.",
    ],
  },
  {
    title: "Cooking pasta",
    keywords: ["cook pasta", "pasta", "boil pasta"],
    steps: [
      "Bring a large pot of water to a rolling boil and salt it generously (it should taste like the sea).",
      "Add the pasta and stir occasionally so it doesn't stick together.",
      "Cook 1-2 minutes less than the package time for al dente texture, tasting to check.",
      "Reserve a cup of starchy pasta water before draining — it helps sauces bind to the noodles.",
      "Drain and immediately toss with sauce; don't rinse it, or the sauce won't stick.",
    ],
  },
  {
    title: "Cooking scrambled eggs",
    keywords: ["scrambled eggs", "cook eggs", "eggs"],
    steps: [
      "Crack eggs into a bowl, add a splash of milk, and whisk until fully blended.",
      "Heat a nonstick pan over low-medium heat with a small pat of butter.",
      "Pour in the eggs and let them sit for a few seconds before gently pushing them with a spatula.",
      "Keep folding gently every 20-30 seconds — low heat and patience prevent rubbery eggs.",
      "Remove from heat while they still look slightly underdone; they'll finish cooking from residual heat. Season with salt at the end.",
    ],
  },
  {
    title: "Grilling burgers or chicken",
    keywords: ["grill", "grilling", "bbq", "barbecue"],
    steps: [
      "Preheat the grill to medium-high and clean the grates with a brush.",
      "Lightly oil the grates or the meat itself to prevent sticking.",
      "For burgers: don't press down on the patties; flip once, around 3-4 minutes per side for medium.",
      "For chicken: cook over medium heat with the lid closed, flipping occasionally to avoid charring.",
      "Use a meat thermometer — 165°F for chicken, 160°F for ground beef — then let meat rest a few minutes before serving.",
    ],
  },
  {
    title: "Basic first aid for a cut or wound",
    keywords: ["first aid", "cut", "bleeding", "wound"],
    steps: [
      "Wash your hands, then apply firm, direct pressure with a clean cloth to stop the bleeding.",
      "Once bleeding slows, rinse the wound gently with clean water to remove debris.",
      "Apply an antiseptic or antibiotic ointment if available.",
      "Cover with a sterile bandage and change it daily or whenever it gets wet or dirty.",
      "Seek medical attention if the cut is deep, won't stop bleeding, or shows signs of infection (redness, swelling, pus).",
    ],
  },
  {
    title: "Treating a minor burn",
    keywords: ["burn", "burnt", "scald"],
    steps: [
      "Cool the burn under cool (not ice-cold) running water for 10-20 minutes immediately.",
      "Remove any tight clothing or jewelry near the area before it swells.",
      "Do not pop any blisters that form.",
      "Cover loosely with a clean, non-stick bandage or sterile gauze.",
      "Seek medical attention for burns larger than a few inches, on the face/hands/joints, or that look white or charred.",
    ],
  },
  {
    title: "Performing the Heimlich maneuver (choking)",
    keywords: ["choking", "heimlich"],
    steps: [
      "Ask 'Are you choking?' — if they can't speak, cough, or breathe, act immediately.",
      "Stand behind the person and wrap your arms around their waist.",
      "Make a fist with one hand and place it just above their navel, grabbing it with your other hand.",
      "Give quick, firm upward thrusts into the abdomen.",
      "Repeat until the object is dislodged or the person can breathe/cough on their own. Call emergency services if it doesn't clear quickly.",
    ],
  },
  {
    title: "Basic CPR steps",
    keywords: ["cpr", "chest compressions", "not breathing"],
    steps: [
      "Check responsiveness and breathing; call emergency services (or have someone else call) immediately.",
      "Lay the person on their back on a firm surface.",
      "Place the heel of one hand on the center of their chest, the other hand on top, fingers interlaced.",
      "Push hard and fast, about 2 inches deep, at a rate of 100-120 compressions per minute (the beat of 'Stayin' Alive' is a common reference).",
      "Continue compressions until emergency help arrives or the person starts breathing — only do rescue breaths if trained.",
    ],
  },
  {
    title: "Acing a job interview",
    keywords: ["interview", "job interview", "handshake"],
    steps: [
      "Research the company beforehand so you can speak to why you want to work there specifically.",
      "Dress one level more formal than the company's everyday dress code.",
      "Arrive 10-15 minutes early, greet with a firm handshake and direct eye contact.",
      "Use the STAR method (Situation, Task, Action, Result) to answer behavioral questions.",
      "Prepare 2-3 thoughtful questions to ask the interviewer about the role or team.",
      "Send a short thank-you email within 24 hours restating your interest.",
    ],
  },
  {
    title: "Writing a resume",
    keywords: ["resume", "cv"],
    steps: [
      "Keep it to one page unless you have 10+ years of relevant experience.",
      "Lead each bullet with an action verb and quantify results where possible ('Increased sales by 20%').",
      "Tailor the skills and experience listed to match the specific job description.",
      "Keep formatting clean and consistent — same font, spacing, and bullet style throughout.",
      "Proofread carefully, then have someone else review it for typos and clarity before sending.",
    ],
  },
  {
    title: "Writing a cover letter",
    keywords: ["cover letter"],
    steps: [
      "Address it to a specific person if possible, not just 'Hiring Manager'.",
      "Open with a strong first line that shows genuine interest in the role, not a generic intro.",
      "In the body, connect 2-3 of your specific experiences directly to what the job needs.",
      "Keep it under one page and avoid simply repeating your resume word for word.",
      "Close with a clear, confident call to action requesting an interview or conversation.",
    ],
  },
  {
    title: "Negotiating a salary",
    keywords: ["salary", "negotiate", "negotiation", "raise"],
    steps: [
      "Research the market rate for the role using sites like Glassdoor or Levels.fyi before any conversation.",
      "Let the employer give the first number when possible.",
      "If you must name a number, anchor slightly above your target to leave room to negotiate down.",
      "Justify your ask with specific accomplishments, skills, or market data — not just want.",
      "Stay calm and friendly; negotiation is a conversation, not a confrontation.",
      "If salary is fixed, ask about signing bonus, extra PTO, or remote flexibility instead.",
    ],
  },
  {
    title: "Building credit and understanding credit scores",
    keywords: ["credit score", "build credit", "credit card"],
    steps: [
      "Get a credit card (even a secured one if you're starting out) and use it for small, regular purchases.",
      "Always pay the full statement balance on time every month — payment history is the biggest scoring factor.",
      "Keep your credit utilization (balance vs. limit) under about 30%, ideally lower.",
      "Avoid opening too many new accounts in a short period, which can temporarily lower your score.",
      "Check your credit report for free annually and dispute any errors you find.",
    ],
  },
  {
    title: "Budgeting your paycheck",
    keywords: ["budget", "budgeting", "paycheck", "saving money"],
    steps: [
      "Calculate your total monthly take-home (after-tax) income first.",
      "Try the 50/30/20 rule as a starting point: 50% needs, 30% wants, 20% savings/debt payoff.",
      "List fixed expenses (rent, bills, subscriptions) separately from variable spending (food, entertainment).",
      "Automate transfers to savings right when you get paid, so saving isn't optional.",
      "Review spending weekly using a budgeting app or simple spreadsheet to catch overspending early.",
    ],
  },
  {
    title: "Filing basic taxes",
    keywords: ["taxes", "file taxes", "tax return"],
    steps: [
      "Gather your documents: W-2s from employers, 1099s for freelance/contract income, and receipts for deductions.",
      "Choose a filing method: free tax software (for simple returns), paid software, or a professional for complex situations.",
      "Decide between standard deduction and itemizing — most people are better off with the standard deduction.",
      "Double-check your direct deposit info for any refund and your personal details for typos.",
      "File before the deadline (typically April 15 in the US) or file for an extension if you need more time.",
    ],
  },
  {
    title: "Table manners and dining etiquette",
    keywords: ["table manners", "dining etiquette", "fork knife"],
    steps: [
      "Wait until everyone is served (or the host says to start) before eating.",
      "Work from the outside in with silverware — outermost utensils are for the first course.",
      "Keep your napkin on your lap, and use it to dab your mouth, not wipe broadly.",
      "Chew with your mouth closed and don't talk with food in your mouth.",
      "When finished, rest your fork and knife together on the plate rather than pushing the plate away.",
    ],
  },
  {
    title: "Tipping etiquette",
    keywords: ["tipping", "how much to tip", "tip"],
    steps: [
      "Sit-down restaurants: tip 18-20% of the pre-tax bill for good service.",
      "Bartenders: $1-2 per drink, or 15-20% of the tab for a full visit.",
      "Hairdressers/barbers: typically 15-20% of the service cost.",
      "Delivery drivers: 15-20% of the order total, with a minimum of a few dollars even for small orders.",
      "Hotel housekeeping: a few dollars per night, left clearly in the room.",
    ],
  },
  {
    title: "Public speaking with confidence",
    keywords: ["public speaking", "speech", "nervous speaking", "presentation"],
    steps: [
      "Know your first and last lines cold — strong openings and closings cover for nerves in the middle.",
      "Practice out loud multiple times, not just in your head, ideally in front of someone.",
      "Slow down deliberately; nervous speakers almost always speak too fast.",
      "Make eye contact with a few friendly faces in the audience instead of staring at notes.",
      "Pause instead of saying 'um' — silence feels longer to you than it does to the audience.",
    ],
  },
  {
    title: "Having a difficult conversation / conflict resolution",
    keywords: ["conflict resolution", "difficult conversation", "argument"],
    steps: [
      "Pick a private, calm moment rather than addressing it in the heat of the moment.",
      "Use 'I' statements ('I felt...') instead of accusatory 'you' statements.",
      "Listen fully before responding — repeat back what you heard to confirm you understood.",
      "Focus on the specific behavior or issue, not generalizations about the person's character.",
      "Agree on a concrete next step or resolution before ending the conversation.",
    ],
  },
  {
    title: "Asking someone out",
    keywords: ["ask someone out", "ask her out", "ask him out", "first date"],
    steps: [
      "Be direct and clear about what you're asking — ambiguity makes it harder for them to say yes.",
      "Suggest a specific, low-pressure activity (coffee, a walk) rather than a vague 'we should hang out sometime'.",
      "Ask in person or by call/text depending on how you usually talk — don't overthink the medium.",
      "If they say no or seem hesitant, accept it gracefully without pressuring them.",
      "For the date itself: pick a place where you can actually talk, put your phone away, and ask questions about them.",
    ],
  },
  {
    title: "Time management basics",
    keywords: ["time management", "procrastination", "productivity"],
    steps: [
      "Write down everything you need to do — an unclear mental list creates stress and dropped tasks.",
      "Each day, pick your top 1-3 priorities and do those before anything else.",
      "Block specific times on your calendar for focused work, not just to-do items with no time attached.",
      "Batch small, similar tasks (emails, errands) together instead of doing them throughout the day.",
      "Build in buffer time between tasks — back-to-back scheduling with zero slack always falls apart.",
    ],
  },
  {
    title: "Tying a bowline knot",
    keywords: ["knot", "bowline", "tie a knot", "rope"],
    steps: [
      "Make a small loop in the rope a few feet from the end (this is the 'rabbit hole').",
      "Pass the working end of the rope up through the loop ('the rabbit comes out of the hole').",
      "Wrap it around the standing part of the rope ('around the tree').",
      "Pass it back down through the loop ('back down the hole').",
      "Pull the standing end to tighten the knot snugly.",
    ],
  },
  {
    title: "Mowing a lawn",
    keywords: ["mow lawn", "mowing", "lawn mower"],
    steps: [
      "Check the mower's oil and fuel, and make sure the blade is sharp for a clean cut.",
      "Set the cutting height appropriately — cutting too short stresses the grass and roots.",
      "Mow in straight, overlapping rows, alternating direction each time you mow to avoid ruts.",
      "Never mow wet grass — it clogs the mower and cuts unevenly.",
      "Leave grass clippings on the lawn (if short) as a natural fertilizer, or bag them if they're long and clumpy.",
    ],
  },
  {
    title: "Washing a car",
    keywords: ["wash car", "car wash", "washing the car"],
    steps: [
      "Rinse the whole car first to remove loose dirt before applying soap, which prevents scratching.",
      "Use a dedicated car-wash soap (not dish soap, which strips wax) with a clean wash mitt.",
      "Wash from top to bottom, rinsing the mitt frequently in a separate bucket of clean water.",
      "Dry with a microfiber towel or chamois immediately to prevent water spots.",
      "Apply wax or sealant every few months to protect the paint.",
    ],
  },
  {
    title: "Essential tools for a basic toolbox",
    keywords: ["toolbox", "basic tools", "tool kit"],
    steps: [
      "Get a mid-size claw hammer and a set of Phillips and flathead screwdrivers.",
      "Add an adjustable wrench and a basic socket set for nuts and bolts of different sizes.",
      "Include a tape measure, a level, and a utility knife for general projects.",
      "Carry a cordless drill/driver — it covers most drilling and screwing tasks at once.",
      "Round it out with pliers, a stud finder, duct tape, and a flashlight or headlamp.",
    ],
  },
  {
    title: "Setting up home Wi-Fi / fixing a slow connection",
    keywords: ["wifi", "router", "internet slow", "home network"],
    steps: [
      "Place the router in a central, open location, off the floor and away from thick walls or metal objects.",
      "Restart the router and modem (unplug both for 30 seconds) — this fixes a large share of connection issues.",
      "Update the router's firmware through its admin app or web page.",
      "Use the 5GHz band for speed at close range, 2.4GHz for range through walls.",
      "If coverage is still weak in parts of the house, add a mesh Wi-Fi extender or access point.",
    ],
  },
  {
    title: "Networking and making small talk",
    keywords: ["small talk", "networking", "introduce myself"],
    steps: [
      "Open with a simple observation or question about the shared context (event, location, mutual contact).",
      "Ask open-ended questions ('What brought you here?') instead of yes/no questions.",
      "Practice active listening — react to what they actually said before changing topics.",
      "Find a genuine point of connection, even a small one, and build on it.",
      "End the conversation gracefully by exchanging contact info or naming a clear next step.",
    ],
  },
  {
    title: "Unjamming a printer",
    keywords: ["printer jam", "paper jam", "printer not working"],
    steps: [
      "Turn off the printer before reaching inside to avoid damaging rollers or gears.",
      "Open every access panel/tray and gently pull jammed paper in the direction it normally feeds — never yank backward.",
      "Check for small torn paper scraps left behind, which cause repeat jams.",
      "Make sure paper is loaded correctly, not overfilled, and matches the tray's size guides.",
      "Power the printer back on and run a test print.",
    ],
  },
];

const FALLBACK_TOPICS = KNOWLEDGE.map((t) => t.title);
